theme: jekyll-theme-slate
title: Machine Learning for Creativity and Design
description: What’s the State of the 'Art' in Machine Learning? The Creativity workshop explores applying the latest ML technologies in art and design.
eventdate: December 13, Online.
